//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WbA2
{
    using System;
    using System.Collections.Generic;
    
    public partial class carti
    {
        public carti()
        {
            this.carti_comandate = new HashSet<carti_comandate>();
        }
    
        public string id_carte { get; set; }
        public string titlu { get; set; }
        public string autor { get; set; }
        public Nullable<double> pret { get; set; }
    
        public virtual ICollection<carti_comandate> carti_comandate { get; set; }
    }
}
