//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WbA2
{
    using System;
    using System.Collections.Generic;
    
    public partial class carti_comandate
    {
        public int id_comanda { get; set; }
        public string id_carte { get; set; }
        public int cantitate { get; set; }
    
        public virtual carti carti { get; set; }
        public virtual comenzi comenzi { get; set; }
    }
}
