//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WbA2
{
    using System;
    using System.Collections.Generic;
    
    public partial class comenzi
    {
        public comenzi()
        {
            this.carti_comandate = new HashSet<carti_comandate>();
        }
    
        public int id_comanda { get; set; }
        public string cnp { get; set; }
        public Nullable<double> valoare { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual ICollection<carti_comandate> carti_comandate { get; set; }
        public virtual clienti clienti { get; set; }
    }
}
