//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WbA2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DenisEntities : DbContext
    {
        public DenisEntities()
            : base("name=DenisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<carti> cartis { get; set; }
        public DbSet<carti_comandate> carti_comandate { get; set; }
        public DbSet<clienti> clientis { get; set; }
        public DbSet<comenzi> comenzis { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int InsertCarte(string id_carte, string titlu, string autor, Nullable<double> pret)
        {
            var id_carteParameter = id_carte != null ?
                new ObjectParameter("id_carte", id_carte) :
                new ObjectParameter("id_carte", typeof(string));
    
            var titluParameter = titlu != null ?
                new ObjectParameter("titlu", titlu) :
                new ObjectParameter("titlu", typeof(string));
    
            var autorParameter = autor != null ?
                new ObjectParameter("autor", autor) :
                new ObjectParameter("autor", typeof(string));
    
            var pretParameter = pret.HasValue ?
                new ObjectParameter("pret", pret) :
                new ObjectParameter("pret", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCarte", id_carteParameter, titluParameter, autorParameter, pretParameter);
        }
    
        public virtual int InsertCarteComandata(Nullable<int> id_comanda, string id_carte, Nullable<int> cantitate)
        {
            var id_comandaParameter = id_comanda.HasValue ?
                new ObjectParameter("id_comanda", id_comanda) :
                new ObjectParameter("id_comanda", typeof(int));
    
            var id_carteParameter = id_carte != null ?
                new ObjectParameter("id_carte", id_carte) :
                new ObjectParameter("id_carte", typeof(string));
    
            var cantitateParameter = cantitate.HasValue ?
                new ObjectParameter("cantitate", cantitate) :
                new ObjectParameter("cantitate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCarteComandata", id_comandaParameter, id_carteParameter, cantitateParameter);
        }
    
        public virtual int InsertClient(string cnp, string nume, string oras, string tel, Nullable<System.DateTime> data_inreg)
        {
            var cnpParameter = cnp != null ?
                new ObjectParameter("cnp", cnp) :
                new ObjectParameter("cnp", typeof(string));
    
            var numeParameter = nume != null ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(string));
    
            var orasParameter = oras != null ?
                new ObjectParameter("oras", oras) :
                new ObjectParameter("oras", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var data_inregParameter = data_inreg.HasValue ?
                new ObjectParameter("data_inreg", data_inreg) :
                new ObjectParameter("data_inreg", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertClient", cnpParameter, numeParameter, orasParameter, telParameter, data_inregParameter);
        }
    
        public virtual int InsertComanda(Nullable<int> id_comanda, string cnp, Nullable<double> valoare, Nullable<System.DateTime> data)
        {
            var id_comandaParameter = id_comanda.HasValue ?
                new ObjectParameter("id_comanda", id_comanda) :
                new ObjectParameter("id_comanda", typeof(int));
    
            var cnpParameter = cnp != null ?
                new ObjectParameter("cnp", cnp) :
                new ObjectParameter("cnp", typeof(string));
    
            var valoareParameter = valoare.HasValue ?
                new ObjectParameter("valoare", valoare) :
                new ObjectParameter("valoare", typeof(double));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertComanda", id_comandaParameter, cnpParameter, valoareParameter, dataParameter);
        }
    
        public virtual int StergeCarte(Nullable<int> id_carte, string titlu, string autor, Nullable<double> pret)
        {
            var id_carteParameter = id_carte.HasValue ?
                new ObjectParameter("id_carte", id_carte) :
                new ObjectParameter("id_carte", typeof(int));
    
            var titluParameter = titlu != null ?
                new ObjectParameter("titlu", titlu) :
                new ObjectParameter("titlu", typeof(string));
    
            var autorParameter = autor != null ?
                new ObjectParameter("autor", autor) :
                new ObjectParameter("autor", typeof(string));
    
            var pretParameter = pret.HasValue ?
                new ObjectParameter("pret", pret) :
                new ObjectParameter("pret", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergeCarte", id_carteParameter, titluParameter, autorParameter, pretParameter);
        }
    
        public virtual int StergeCartiComandate(Nullable<int> id_comanda, string id_carte, Nullable<int> cantitate)
        {
            var id_comandaParameter = id_comanda.HasValue ?
                new ObjectParameter("id_comanda", id_comanda) :
                new ObjectParameter("id_comanda", typeof(int));
    
            var id_carteParameter = id_carte != null ?
                new ObjectParameter("id_carte", id_carte) :
                new ObjectParameter("id_carte", typeof(string));
    
            var cantitateParameter = cantitate.HasValue ?
                new ObjectParameter("cantitate", cantitate) :
                new ObjectParameter("cantitate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergeCartiComandate", id_comandaParameter, id_carteParameter, cantitateParameter);
        }
    
        public virtual int StergeClient(string cnp, string nume, string oras, string tel, Nullable<System.DateTime> data_inreg)
        {
            var cnpParameter = cnp != null ?
                new ObjectParameter("cnp", cnp) :
                new ObjectParameter("cnp", typeof(string));
    
            var numeParameter = nume != null ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(string));
    
            var orasParameter = oras != null ?
                new ObjectParameter("oras", oras) :
                new ObjectParameter("oras", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var data_inregParameter = data_inreg.HasValue ?
                new ObjectParameter("data_inreg", data_inreg) :
                new ObjectParameter("data_inreg", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergeClient", cnpParameter, numeParameter, orasParameter, telParameter, data_inregParameter);
        }
    
        public virtual int StergeComenzi(Nullable<int> id_comanda, string cnp, Nullable<double> valoare, Nullable<System.DateTime> data)
        {
            var id_comandaParameter = id_comanda.HasValue ?
                new ObjectParameter("id_comanda", id_comanda) :
                new ObjectParameter("id_comanda", typeof(int));
    
            var cnpParameter = cnp != null ?
                new ObjectParameter("cnp", cnp) :
                new ObjectParameter("cnp", typeof(string));
    
            var valoareParameter = valoare.HasValue ?
                new ObjectParameter("valoare", valoare) :
                new ObjectParameter("valoare", typeof(double));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergeComenzi", id_comandaParameter, cnpParameter, valoareParameter, dataParameter);
        }
    
        public virtual int UpdateCarte(Nullable<int> id_carte, string titlu, string autor, Nullable<double> pret)
        {
            var id_carteParameter = id_carte.HasValue ?
                new ObjectParameter("id_carte", id_carte) :
                new ObjectParameter("id_carte", typeof(int));
    
            var titluParameter = titlu != null ?
                new ObjectParameter("titlu", titlu) :
                new ObjectParameter("titlu", typeof(string));
    
            var autorParameter = autor != null ?
                new ObjectParameter("autor", autor) :
                new ObjectParameter("autor", typeof(string));
    
            var pretParameter = pret.HasValue ?
                new ObjectParameter("pret", pret) :
                new ObjectParameter("pret", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCarte", id_carteParameter, titluParameter, autorParameter, pretParameter);
        }
    
        public virtual int UpdateCartiComandate(Nullable<int> id_comanda, string id_carte, Nullable<int> cantitate)
        {
            var id_comandaParameter = id_comanda.HasValue ?
                new ObjectParameter("id_comanda", id_comanda) :
                new ObjectParameter("id_comanda", typeof(int));
    
            var id_carteParameter = id_carte != null ?
                new ObjectParameter("id_carte", id_carte) :
                new ObjectParameter("id_carte", typeof(string));
    
            var cantitateParameter = cantitate.HasValue ?
                new ObjectParameter("cantitate", cantitate) :
                new ObjectParameter("cantitate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCartiComandate", id_comandaParameter, id_carteParameter, cantitateParameter);
        }
    
        public virtual int UpdateClient(string cnp, string nume, string oras, string tel, Nullable<System.DateTime> data_inreg)
        {
            var cnpParameter = cnp != null ?
                new ObjectParameter("cnp", cnp) :
                new ObjectParameter("cnp", typeof(string));
    
            var numeParameter = nume != null ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(string));
    
            var orasParameter = oras != null ?
                new ObjectParameter("oras", oras) :
                new ObjectParameter("oras", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var data_inregParameter = data_inreg.HasValue ?
                new ObjectParameter("data_inreg", data_inreg) :
                new ObjectParameter("data_inreg", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateClient", cnpParameter, numeParameter, orasParameter, telParameter, data_inregParameter);
        }
    
        public virtual int UpdateComanda(Nullable<int> id_comanda, string cnp, Nullable<double> valoare, Nullable<System.DateTime> data)
        {
            var id_comandaParameter = id_comanda.HasValue ?
                new ObjectParameter("id_comanda", id_comanda) :
                new ObjectParameter("id_comanda", typeof(int));
    
            var cnpParameter = cnp != null ?
                new ObjectParameter("cnp", cnp) :
                new ObjectParameter("cnp", typeof(string));
    
            var valoareParameter = valoare.HasValue ?
                new ObjectParameter("valoare", valoare) :
                new ObjectParameter("valoare", typeof(double));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateComanda", id_comandaParameter, cnpParameter, valoareParameter, dataParameter);
        }
    }
}
